# build and release chimp-cli

name: build-release-chimpcli

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: test
        # let's pretend we wrote any automated tests
        run: dotnet test
      - name: publish framework-dependent executables
        run: |
          dotnet msbuild -t:PublishAllRids -p:Configuration=Release -p:SelfContained=false
          mkdir -p out
          zip -j out/chimp-win-x64.zip Chimp/bin/Release/net8.0/win-x64/publish/chimp.exe CHANGELOG.md README.md
          tar czf out/chimp-osx-x64.tar.gz -C Chimp/bin/Release/net8.0/osx-x64/publish chimp ../../../../../../CHANGELOG.md ../../../../../../README.md
          tar czf out/chimp-linux-x64.tar.gz -C Chimp/bin/Release/net8.0/linux-x64/publish chimp ../../../../../../CHANGELOG.md ../../../../../../README.md
      - name: publish self-contained executables
        # disabled for the time being because it uses a lot of github storage
        if: false
        run: |
          dotnet msbuild -t:PublishAllRids -p:Configuration=Release -p:SelfContained=true
          mkdir -p out
          zip -j out/chimp-win-x64-selfcontained.zip Chimp/bin/Release/net8.0/win-x64/publish/chimp.exe CHANGELOG.md README.md
          tar czf out/chimp-osx-x64-selfcontained.tar.gz -C Chimp/bin/Release/net8.0/osx-x64/publish chimp ../../../../../../CHANGELOG.md ../../../../../../README.md
          tar czf out/chimp-linux-x64-selfcontained.tar.gz -C Chimp/bin/Release/net8.0/linux-x64/publish chimp ../../../../../../CHANGELOG.md ../../../../../../README.md
      - name: upload publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish-result
          path: |
            CHANGELOG-RELEASE.md
            out
          retention-days: 3
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: download publish artifacts
        uses: actions/download-artifact@v4
        with:
          name: publish-result
      - name: get git tag version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: add version to artifact names
        run: |
          mv out/chimp-win-x64.zip out/chimp-win-x64-${{ env.RELEASE_VERSION }}.zip
          mv out/chimp-osx-x64.tar.gz out/chimp-osx-x64-${{ env.RELEASE_VERSION }}.tar.gz
          mv out/chimp-linux-x64.tar.gz out/chimp-linux-x64-${{ env.RELEASE_VERSION }}.tar.gz
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG-RELEASE.md
          files: |
            out/chimp-win-x64-${{ env.RELEASE_VERSION }}.zip
            out/chimp-osx-x64-${{ env.RELEASE_VERSION }}.tar.gz
            out/chimp-linux-x64-${{ env.RELEASE_VERSION }}.tar.gz
